### ISSUE TITLE
type error split

### ISSUE THREAD

**Issue by hklages** [cinhcet/node-red-contrib-upnp#1]
Please have a look at this message: 

![upnp - errror](https://user-images.githubusercontent.com/17273119/84521439-4d1d5180-acd5-11ea-9eac-b349a785cf88.png)

**Comment by cinhcet** [comment]
Does this happen always or just sometimes? 

Can you add `console.log(parsedData);` before that line here https://github.com/cinhcet/node-red-contrib-upnp/blob/master/upnp/upnp.js#L517
and post what it spits outs.

This would speed up the debugging, but I think I understand the problem now. Give me a second to fix it

Maybe it was not a good idea to point you that my library :-) Now all the bugs pop up that have never with my devices

**Comment by cinhcet** [comment]
ok, I think I have a small bug there, but sonos is definitively not adhering to the specs, otherwise the bug would not happen. I need to see what they spit out to implement a fix for that

**Comment by cinhcet** [comment]
Can you check if the current version fixes it?

I made it more robust, although I think I was indeed adhering to the specifications

**Comment by hklages** [comment]
I installed the new version. The type error occurred only once. 
Lets see.

**Comment by hklages** [comment]
so far no error occured. Thanks.
