### ISSUE TITLE
No AVTransport events

### ISSUE THREAD

**Issue by hklages** [cinhcet/node-red-contrib-upnp#2]
Neither node MediaRender nor node receive event with `urn:schemas-upnp-org:service:AVTransport:1` receive any events - e. g. when start/stop/pause the music. 

2020-06-12 1843: Now a few messages arrive - e. g. i change from playing a station to playing the SONOS queue.

Any idea. The log does not say anything. Both nodes have status green.

**Comment by cinhcet** [comment]
do other events work?

**Comment by hklages** [comment]
**urn:schemas-upnp-org:service:GroupRenderingControl:1**
group mute, group volume, volume, ... work perfect. 

**urn:schemas-upnp-org:service:RenderingControl:1**
volume works, but mute does not work. 

**urn:schemas-upnp-org:service:AVTransport:1**
no event when stop/play

queue next track, etc, also do not work. 

Strange.

**Comment by cinhcet** [comment]
this indeed is strange.

Could you add before line https://github.com/cinhcet/node-red-contrib-upnp/blob/master/upnp/upnp.js#L136
console.log(eventMessage);
and then do a play or stop and look if something comes in the console?

If not, then I really don't know how to debug that without having access to the device. Have you controlled the sonos with a different UPnP control point yet and those events have worked?

**Comment by hklages** [comment]
Hi I added node.log and that does not show more events. 

I agree, we should not investigate longer - don't wont to waste your time. 
It seems that SONOS is too far away from standard upnp. 

Thanks a lot  - it was interesting to see how UPNP works. 

I close this issue.
